import Navbar from '@/components/Navbar'
import {CartProvider} from '@/context/CartContext'
import './globals.css'

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {


  return (
    <html lang="en">
      <body className='container mx-auto px-4'>
        <CartProvider>
        <Navbar/>
        {children}
        </CartProvider>
      </body>
    </html>
  )
}